Fix variable naming and usage
Pennsieve/discover-service pull request #38
Opened 2023-01-11 21:13 UTC by darrell-d

2023-01-11 21:41 UTC, jfromme requested changes
See comment, but basically, `use1` should also be a variable value, not hardcoded.

2023-01-12 21:05 UTC, darrell-d commented on terraform/variables.tf
> +  s3_glue_location= "s3://pennsieve-${var.environment_name}-${var.service_name}-publish-logs-use1/${var.environment_name}/${var.service_name}-publish/s3"
Updated in new push

2023-01-12 21:11 UTC, darrell-d commented
Responded to the `use1` comment.

Ran terraform plan, shows that my glue changes look good for non-prod, however there are a series of other things it's modifying that I didn't touch. Seems like a series of items tf has decided need to be replaced. See below:

<pre>
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place
-/+ destroy and then create replacement
+/- create replacement and then destroy
 <= read (data resources)

Terraform will perform the following actions:

  # module.ecs_service_alb.aws_ecs_service.ecs_service will be updated in-place
  ~ resource "aws_ecs_service" "ecs_service" {
        id                                 = "arn:aws:ecs:us-east-1:941165240011:service/dev-ecs-cluster-use1/dev-discover-service-use1"
        name                               = "dev-discover-service-use1"
        tags                               = {}
      ~ task_definition                    = "arn:aws:ecs:us-east-1:941165240011:task-definition/dev-discover-service-use1:55" -> (known after apply)
        # (14 unchanged attributes hidden)




        # (4 unchanged blocks hidden)
    }

  # module.ecs_service_alb.aws_ecs_task_definition.ecs_task_definition must be replaced
+/- resource "aws_ecs_task_definition" "ecs_task_definition" {
      ~ arn                      = "arn:aws:ecs:us-east-1:941165240011:task-definition/dev-discover-service-use1:55" -> (known after apply)
      ~ container_definitions    = jsonencode(
          ~ [ # forces replacement
              ~ {
                  - mountPoints      = [] -> null
                  ~ portMappings     = [
                      ~ {
                          - hostPort      = 0 -> null
                            # (2 unchanged elements hidden)
                        },
                    ]
                  - volumesFrom      = [] -> null
                    # (8 unchanged elements hidden)
                } # forces replacement,
              ~ {
                  - essential        = true -> null
                  ~ image            = "pennsieve/discover-service:56-e7ec47d" -> "pennsieve/discover-service:test"
                  - portMappings     = [] -> null
                  - volumesFrom      = [] -> null
                    # (6 unchanged elements hidden)
                } # forces replacement,
            ]
        )
      ~ id                       = "dev-discover-service-use1" -> (known after apply)
      + network_mode             = (known after apply)
      - requires_compatibilities = [] -> null
      ~ revision                 = 55 -> (known after apply)
      - tags                     = {} -> null
      ~ tags_all                 = {} -> (known after apply)
        # (3 unchanged attributes hidden)
    }

  # module.ecs_service_alb.null_resource.confirm_healthy_deployment_10_minute_timeout must be replaced
-/+ resource "null_resource" "confirm_healthy_deployment_10_minute_timeout" {
      ~ id       = "3675025103987294638" -> (known after apply)
      ~ triggers = { # forces replacement
          ~ "ecs_task_definition_arn" = "arn:aws:ecs:us-east-1:941165240011:task-definition/dev-discover-service-use1:55" -> (known after apply)
        }
    }

  # module.service_module.data.aws_iam_policy_document.iam_policy_document will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "iam_policy_document"  {
      ~ id      = "3986460931" -> (known after apply)
      ~ json    = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = "kms:Decrypt"
                      - Effect   = "Allow"
                      - Resource = "arn:aws:kms:us-east-1:941165240011:key/alias/aws/ssm"
                      - Sid      = "KMSDecryptPermissions"
                    },
                  - {
                      - Action   = "secretsmanager:ListSecrets"
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = "SecretsManagerListPermissions"
                    },
                  - {
                      - Action   = [
                          - "ssm:GetParametersByPath",
                          - "ssm:GetParameters",
                          - "ssm:GetParameter",
                        ]
                      - Effect   = "Allow"
                      - Resource = "arn:aws:ssm:us-east-1:941165240011:parameter/dev/discover-service/*"
                      - Sid      = "SSMPermissions"
                    },
                  - {
                      - Action   = "states:StartExecution"
                      - Effect   = "Allow"
                      - Resource = [
                          - "arn:aws:states:us-east-1:941165240011:stateMachine:dev-discover-release-state-machine-use1",
                          - "arn:aws:states:us-east-1:941165240011:stateMachine:dev-discover-publish-state-machine-use1",
                        ]
                      - Sid      = "StartStateMachine"
                    },
                  - {
                      - Action   = [
                          - "glue:GetTable",
                          - "glue:GetCatalogImportStatus",
                        ]
                      - Effect   = "Allow"
                      - Resource = [
                          - "arn:aws:glue:us-east-1:941165240011:table/s3_access_logs_db/*",
                          - "arn:aws:glue:us-east-1:941165240011:database/s3_access_logs_db",
                          - "arn:aws:glue:us-east-1:941165240011:catalog",
                        ]
                      - Sid      = "GlueGetTable"
                    },
                  - {
                      - Action   = [
                          - "athena:StartQueryExecution",
                          - "athena:GetQueryResultsStream",
                          - "athena:GetQueryExecution",
                        ]
                      - Effect   = "Allow"
                      - Resource = "arn:aws:athena:us-east-1:941165240011:workgroup/primary"
                      - Sid      = "AthenaQueryExecution"
                    },
                  - {
                      - Action   = [
                          - "sqs:ReceiveMessage",
                          - "sqs:DeleteMessage",
                        ]
                      - Effect   = "Allow"
                      - Resource = "arn:aws:sqs:us-east-1:941165240011:dev-discover-publish-queue-use1"
                      - Sid      = "SQSReceiveMessages"
                    },
                  - {
                      - Action   = [
                          - "kms:GenerateDataKey",
                          - "kms:Decrypt",
                        ]
                      - Effect   = "Allow"
                      - Resource = "arn:aws:kms:us-east-1:941165240011:key/3aea235e-7abd-4e7d-bd83-3448eecffacf"
                      - Sid      = "KMSDecryptMessages"
                    },
                  - {
                      - Action   = [
                          - "s3:PutObject",
                          - "s3:ListMultipartUploadParts",
                          - "s3:ListBucketMultipartUploads",
                          - "s3:ListBucket",
                          - "s3:GetObject",
                          - "s3:GetBucketLocation",
                          - "s3:DeleteObject",
                          - "s3:CreateBucket",
                          - "s3:AbortMultipartUpload",
                        ]
                      - Effect   = "Allow"
                      - Resource = [
                          - "arn:aws:s3:::pennsieve-dev-discover-publish-logs-use1/*",
                          - "arn:aws:s3:::pennsieve-dev-discover-publish-logs-use1",
                        ]
                      - Sid      = "AthenaResultBucket"
                    },
                  - {
                      - Action   = [
       [...]

2023-04-13 19:38 UTC, darrell-d reviewed
Looks good, thanks for cleaning up the spelling error

2023-04-13 19:53 UTC, jfromme approved these changes

2023-04-13 19:53 UTC, merged